name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    name: Run My Python Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python Script
        run: python hello.py
